num_layers: 5
hidden_column_dim: 16
preprocessor_dim: 32
share_weights: false
x_dim: 16 # Max sequence length
y_dim:
encoder_lr: 0.5
num_iters: 3
decoder_lr: 0.5
up_radius: 4
down_radius: 4
pad: false
pad_value: "-inf"
rng_seed: 42
schedule_type: "exponential"
temporal_horizon: 4
log_losses: true
